### ISSUE TITLE
Support for imaging interface

### ISSUE THREAD

**Issue by DuFF14** [OSVR/Managed-OSVR#20]
Required for Leap Motion Image Hands and pass-through video.
https://github.com/OSVR/OSVR-Leap-Motion/issues/8
https://github.com/OSVR/OSVR-Unity/issues/66

**Comment by rpavlik** [comment]
The questions I see are:
- how to best represent the image data in .NET
- whether we can do buffer sharing aka directly using the buffer from ClientKit (unlikely) or if we should perform a copy then immediately release the buffer we get from ClientKit - this is probably the case since garbage collection means we wouldn't necessarily release the buffer as soon as we're done, and that could block the ring buffer keeping the server from producing more frames.

**Comment by JeroMiya** [comment]
This was on my list to research. In theory it should be possible to marshall an array of simple data (unsigned char\* qualifies) without copying and without GC managing the buffer's lifetime, but I'm unsure on the details, particularly since the data is marshalled through a function pointer callback into managed code.

As for representation - just raw data in Managed-OSVR I think, same format as it comes from osvr-core with no conversion. It should be up to OSVR-Unity/MonoGame to copy the buffer data into an appropriate pixel format for rendering. Otherwise we might be doing an unnecessary pixel format conversion.

**Comment by JeroMiya** [comment]
Closed by: https://github.com/OSVR/Managed-OSVR/pull/27
